# Generated by Django 5.0.1 on 2024-07-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_code_businessunit_bu_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='bu_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='dep_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
