# Generated by Django 5.0.1 on 2024-07-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_businessunit_bu_code_alter_department_dep_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='ftem_ls',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='ftg_grav_ls',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='hem_ls',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='mag_grad_ls',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='magnetometry_ls',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='spectrometry_ls',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='standard_grav_ls',
        ),
    ]
