# Generated by Django 5.0.1 on 2024-07-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_proposal_ftem_ls_remove_proposal_ftg_grav_ls_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ftem_ls',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ftg_grav_ls',
        ),
        migrations.RemoveField(
            model_name='project',
            name='hem_ls',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mag_grad_ls',
        ),
        migrations.RemoveField(
            model_name='project',
            name='magnetometry_ls',
        ),
        migrations.RemoveField(
            model_name='project',
            name='spectrometry_ls',
        ),
        migrations.RemoveField(
            model_name='project',
            name='standard_grav_ls',
        ),
    ]
