# Generated by Django 5.0.1 on 2024-07-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_ftem_ls_remove_project_ftg_grav_ls_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ftem',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ftg_grav',
        ),
        migrations.RemoveField(
            model_name='project',
            name='hem',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mag_grad',
        ),
        migrations.RemoveField(
            model_name='project',
            name='magnetometry',
        ),
        migrations.RemoveField(
            model_name='project',
            name='spectrometry',
        ),
        migrations.RemoveField(
            model_name='project',
            name='standard_grav',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='ftem',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='ftg_grav',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='hem',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='mag_grad',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='magnetometry',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='spectrometry',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='standard_grav',
        ),
        migrations.AddField(
            model_name='project',
            name='asg',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Airborne Scalar Gravity'),
        ),
        migrations.AddField(
            model_name='project',
            name='fagg',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Airborne Gravity Gradiometer and Magnetic (Falcon)'),
        ),
        migrations.AddField(
            model_name='project',
            name='fmagrad',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Airborne Magnetics & Radiometrics'),
        ),
        migrations.AddField(
            model_name='project',
            name='gst',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Geospatial Technologies'),
        ),
        migrations.AddField(
            model_name='project',
            name='hagg',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Helicopter Gravity Gradiometer and Magnetic (Falcon)'),
        ),
        migrations.AddField(
            model_name='project',
            name='helitem',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Helicopter Time Domain Electromagnetic and Magnetic'),
        ),
        migrations.AddField(
            model_name='project',
            name='hmagrad',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Helicopter Magnetics & Radiometrics'),
        ),
        migrations.AddField(
            model_name='project',
            name='midas',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Helicopter Magnetics Gradient & Radiometrics'),
        ),
        migrations.AddField(
            model_name='project',
            name='proc_magrad',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Magnetic and Radiometric Processing'),
        ),
        migrations.AddField(
            model_name='project',
            name='tempest',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Airborne Time Domain Electromagnetic and Magnetic'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asg',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Airborne Scalar Gravity'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='fagg',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Airborne Gravity Gradiometer and Magnetic (Falcon)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='fmagrad',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Airborne Magnetics & Radiometrics'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='gst',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Geospatial Technologies'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='hagg',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Helicopter Gravity Gradiometer and Magnetic (Falcon)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='helitem',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Helicopter Time Domain Electromagnetic and Magnetic'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='hmagrad',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Helicopter Magnetics & Radiometrics'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='midas',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Helicopter Magnetics Gradient & Radiometrics'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='proc_magrad',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Magnetic and Radiometric Processing'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='tempest',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Airborne Time Domain Electromagnetic and Magnetic'),
        ),
    ]
