# Generated by Django 5.0.1 on 2024-07-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_proposal_business_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='business_units',
        ),
    ]
